---
title: "Dota2_Project"
author: "Vivi He"
date: "3/27/2017"
output: pdf_document
---

# Import data
```{r}
# load dateframes 
d1 = read.csv("dota2Test.csv")
d2 = read.csv("Hero_Info.csv")
```

# Clean data
```{r}
# remove hero names, ids, hero types coulumns of d2
# to get hero_info data
hero_info = as.matrix(d2[, -c(1,2,3)])

# get type column of d2 to get hero_type vector
# change it to a catagorical vector
hero_type = as.factor(d2[, 3])
class(hero_type)

# remove the first four columns of d1
# (flag indicating winner, cluster_id, game mode and game type) 
# to get team_configuration matrix
game_configuration = as.matrix(d1[, -c(1,2,3,4)])

# get flag indicating winner column of d1 to get game_result vector
game_result = d1[, 1]
game_result = as.matrix(game_result, col = 1)
colnames(game_result) = "game_result"
```

# Construct data matrice
## Dire score
```{r}
# build an empty matrix called dire_side with 10 columns
dire_side = matrix(ncol = 10)
# for each row (each game match)
for (i in 1:length(game_result)) {
  # set game_configuration to -1 and get heroes indices for hero_info
  # get dire_heroes_picked using the indices
  dire_heroes_picked = hero_info[(game_configuration[i,] == -1), ]
  # sum the score of dire_heroes_picked
  # and put it into dire_side matrix
  dire_side = rbind(dire_side, colSums(dire_heroes_picked))
}
# remove the first row of dire_side matrix
# because R stores NA for empty matrices by defalut
dire_side = dire_side[-1,]

# column bind with the modified game_result vector
# the game_result vector is modified 
  # so that 0 indicates loss, and 1 indicates win
dire_score = cbind(1 - (game_result + 1)/2, dire_side)
```

## Radiant score
```{r}
# repeat for radiant side
radiant_side = matrix(ncol = 10)
for (i in 1:length(game_result)) {
  # set game_configuration to 1 and get heroes indices for hero_info
  # get dire_heroes_picked using the indices
  radiant_heroes_picked = hero_info[(game_configuration[i,] == 1), ]
  radiant_side = rbind(radiant_side, colSums(radiant_heroes_picked))
}
radiant_side = radiant_side[-1,]

# column bind with the modified game_result vector
# the game_result vector is modified 
  # so that 0 indicates loss, and 1 indicates win
radiant_score = cbind((game_result + 1)/2, radiant_side)
```

## Combine and get total score
```{r}
# row bind dire_score matrix and radiant_score to get score matrix
score = rbind(dire_score, radiant_score)
```

# Data analysis part 1 
## PCA on hero_info data
```{r}
# center and scale data (make data mean = 0 and variance = 1)
hi.pca = prcomp(hero_info, center = T, scale = T)

# print() function 
# returns the standard deviation of each of the PCs
# returns their rotation (or loadings), 
  # which are the coefficients of the linear combinations of the continuous variables.
print(hi.pca)
hi.pca $ sdev
hi.var = hi.pca $ sdev ^ 2
hi.var
pve = hi.var / sum(hi.var)
pve

# plot() function 
# returns a plot of the variances (y-axis) associated with the PCs (x-axis).
# useful to decide how many PCs to retain for further analysis. 
plot(pve, xlab="Principal Component", 
     ylab="Proportion of Variance Explained", ylim=c(0,1),type='b')
plot(cumsum(pve), xlab="Principal Component", 
     ylab="Cumulative Proportion of Variance Explained", ylim=c(0,1),type='b')

# summary() function
# the first row describe again the standard deviation of each PC
# the second row shows the proportion of the variance in the data explained by each component 
# third row describe the cumulative proportion of explained variance
summary(hi.pca)
```

## PCA plot
```{r}
library(devtools)
install_github("ggbiplot", "vqv")
library(ggbiplot)
```

```{r}
g1 = ggbiplot(hi.pca, obs.scale = 1, var.scale = 1, 
             groups = hero_type, ellipse = TRUE, circle = TRUE) 

g1 = g1 + scale_color_discrete(name = '') 
g1 = g1 + theme(legend.direction = 'horizontal', 
                legend.position = 'top')

g2 = ggbiplot(hi.pca, obs.scale = 1, var.scale = 1, 
             groups = hero_type, ellipse = TRUE, circle = TRUE, 
             labels = d2[,"Name"])

g2 = g2 + scale_color_discrete(name = '') 
g2 = g2 + theme(legend.direction = 'horizontal', 
                legend.position = 'top')

print(g1)
print(g2)
```

# Data analysis part 2
## NN on team features and game result
The goal is to see what kind of game configuration (score of features) leads to win. 
```{r}
# install.packages("neuralnet")
library(neuralnet)

# randaom pick 500 rows of the score data be the trainning data
set.seed(2)
train = sample(20586, 500)
score_train = score[train, ]

# ten features as trainning input
Complexity = score_train[,"Complexity"]
Jungler = score_train[,"Jungler"]
Pusher = score_train[,"Pusher"]
Support = score_train[,"Supprt"]
Carry = score_train[,"Carry"]
Nuker = score_train[,"Nuker"]
Initiator = score_train[,"Initiator"]
Disabler = score_train[,"Disabler"]
Durable = score_train[,"Durable"]
Escape = score_train[,"Escape"]

# game result as trainning output
result_train = score_train[, "game_result"]
features_train = score_train[, -1]

# train the neural network
# going to have 10 hidden layers
# threshold is a numeric value specifying the threshold for the partial
  # derivatives of the error function as stopping criteria
net_game_result = neuralnet(result_train ~ Complexity + Jungler + 
                              Pusher + Support + Carry + Nuker +
                              Initiator + Disabler + Durable + Escape,
                            score_train, 
                            hidden = 10, threshold = 0.01,
                            linear.output = F)

# plot the neural network
plot(net_game_result)

# test the neural network on 20 random picked training data
test = sample(20586,20)
score_test = score[test, ]

# run them through the neural network
net_result_test = compute(net_game_result, score_test[,-1]) 

# Lets see what properties net.sqrt has
ls(net_result_test)
net_result_test $ net.result

# Lets create a binary result
nn_binary_result_test = as.integer(net_result_test $ net.result >= 0.5)
print(nn_binary_result_test)

# Lets calculate the test MSE
MSE_test = sum((score_test[,1]-nn_binary_result_test)^2)/length(score_test[,1])
MSE_test
```
